version: '3.8'

services:
  coturn:
    image: coturn/coturn
    container_name: coturn
    restart: always
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "50000-50100:50000-50100/udp"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    command: ["-c", "/etc/coturn/turnserver.conf"]
