server:
  port: 8080

spring:
  application:
    name: webrtc-signaling-server

logging:
  level:
    com.example.signaling: INFO
    org.springframework.web.socket: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

api:
  v1:
    request:
      limit: 400